### ISSUE TITLE
mmap not available on Google App Engine

### ISSUE THREAD

**Issue by GoogleCodeExporter** [scott-griffiths/bitstring#116]
```
mmap is not supported on Google App Engine (GAE). I am successfully using 
bitstring on GAE if I get rid of instances of the MmapByteArray class and don't 
use constbitarray or files (which is fine for my needs). I've included a monkey 
patch to do that based on the absence of the mmap module. I'm sure there's a 
better way, but you might consider separating out the feature set so that the 
library may be used on GAE.

Thanks for the great work!
```

Original issue reported on code.google.com by `mbogos...@gmail.com` on 6 Aug 2011 at 6:19

Attachments:
* [mmap.patch](https://storage.googleapis.com/google-code-attachments/python-bitstring/issue-116/comment-0/mmap.patch)

**Comment by scott-griffiths** [comment]
Closing as it probably works and no one seems to care enough if it doesn't.

**Comment by f14c0** [comment]
Well  i came  arround  to this  issue ..

I'm  currently using GAE (python27),  but  when I try to import bitstring ...still getting  the  error:

 **ImportError**: No module named mmap
