### ISSUE TITLE
Jython support for bitString

### ISSUE THREAD

**Issue by Fyphon** [scott-griffiths/bitstring#147]
bitstring does not work in Jython 2.7.x out of the box but can be hacked to work with the following changes to bitstring.py

1) comment out #import mmap 
   and line ~ 412
   #self.filemap = mmap.mmap(source.fileno(), 0, access=mmap.ACCESS_READ)
This means x = BitArray(filename = inFile) no longer works, but the same effect can be achieved with 
x= BitArray(bytes = open(inFile, 'rb').read() )
3) comment out all the **slots** = (xxx) optimizations. These only work in cPython.

**Comment by scott-griffiths** [comment]
I'm probably not going to try to explicitly add Jython support as I don't think it's used often enough to justify my testing overhead, but I'm sure those changes could be helpful to others (or to me if I change my mind!)
