### ISSUE TITLE
 No such file or directory: 'README.txt' when running "python setup.py install"

### ISSUE THREAD

**Issue by stephenmm** [scott-griffiths/bitstring#149]
Steps:

git clone https://github.com/scott-griffiths/bitstring ~/Downloads/bitstring
pushd ~/Downloads/bitstring
python setup.py install 
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    kwds = {'long_description': open('README.txt').read()}
IOError: [Errno 2] No such file or directory: 'README.txt'

I was able to fix it with this:
mv README.rst README.txt

But I thought I should mention it.

Other info:
Python 2.7.6 (default, Nov 19 2013, 22:43:44) 
[GCC 4.1.2] on linux2

**Comment by flynnsark** [comment]
This should be solved in the `setup.py`. I created a pull request.

**Comment by scott-griffiths** [comment]
Thanks - sorry I didn't see this until recently and I had totally the wrong branch as master which was the real cause of the problems (bad transition from google code). Should be solved now.
