### ISSUE TITLE
Clarify necessity of cython

### ISSUE THREAD

**Issue by krichter722** [scott-griffiths/bitstring#155]
The current `setup.py` doesn't make sense because `_cbitstring.c` is generated by `cython` and thus not managed by `git`, but the extension is supposed to use it if `cython` isn't installed.

experienced with 6c6aadd

**Comment by scott-griffiths** [comment]
That's only true of the current trunk, which isn't considered stable. None of the released versions need Cython. Unfortunately people seem to be using my development branch instead of a released stable version since it moved to git-hub. Not sure of a good way to discourage this!

**Comment by scott-griffiths** [comment]
Okay - so I need to move my branches around so that master is deployable. I hadn't looked enough at the changes I needed to do after getting kicked off google-code.

**Comment by scott-griffiths** [comment]
master branch no longer needs cython (new cythonisation branch created).
