### ISSUE TITLE
bitstring 3.1.4 pip install error

### ISSUE THREAD

**Issue by thorink** [scott-griffiths/bitstring#158]
When i want to install the new 3.1.4 release under a Python 3.5 virtualenv, pip crashes with the following error message:
```
Collecting bitstring
  Using cached bitstring-3.1.4.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/07/k2nd3g193sz9_q7v4vxw7lt00000gn/T/pip-build-5ouk7d7c/bitstring/setup.py", line 7, in <module>
        kwds = {'long_description': open('README.rst').read()}
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
```

This particular message is from a Mac, but the same thing happens also on my ARM Box with Debian.

Any ideas whats the issue here? Please ask, if you have any questions about my environment. I would be glad to help.

**Comment by thorink** [comment]
It seems that the README.rst is not in the zip file. What I did is `pip install bitstring==3.1.4 --download .` and inspected the resulting bitstring-3.1.4.zip.

I'm not into Python packaging, but on [SO](http://stackoverflow.com/a/29158121) someone mentioned to include the README.rst into the MANIFEST.in file.

**Comment by adityapatadia** [comment]
+1

**Comment by KarelJakubec** [comment]
The same happens when installing with python 2.7.11 virtualenv. And worse, version 3.1.3 disappeared from pypi so for new installations one must "downgrade" bitsring to 3.1.2, which is still present. :)

**Comment by jgillick** [comment]
Seeing the same thing. We had 3.1.3 in our requirements file, which is no longer available on pypi.

**Comment by BinyaminSharet** [comment]
As a temporary solution, I use "bitstring!=3.14" as a dependency.

**Comment by scott-griffiths** [comment]
Sorry guys - I've been having problems with uploading a new version to PyPI. I'm trying to revert back to 3.1.3 as soon as possible.

**Comment by scott-griffiths** [comment]
It seems I can't ever put 3.1.3 back on PyPI, which is rather annoying. I will look to fix the problem with the README file and retry the 3.1.4 upload this evening.

In the meantime I think everyone will now be getting 3.1.2 from PyPI

**Comment by scott-griffiths** [comment]
Should be fixed. Version 3.1.4 is now available through PyPI.
