### ISSUE TITLE
3.1.3 Missing from pypi

### ISSUE THREAD

**Issue by jgillick** [scott-griffiths/bitstring#159]
My organization was using 3.1.3, which is no longer available from pypi. Is this version no longer supported?

**Comment by scott-griffiths** [comment]
I've been having problems uploading 3.1.4 to PyPI, which meant I accidentally deleted the 3.1.3 file. There doesn't seem to be any way of putting it back, and I can't yet get a new version up there. 

So 3.1.3 is still available, just not from PyPI until I can get this sorted. And 3.1.4 will be available as soon as I get that sorted.

http://stackoverflow.com/questions/28708705/pypi-400-upload-error

**Comment by scott-griffiths** [comment]
I can't re-upload 3.1.3 to PyPI (it won't let me), but 3.1.4 is now available and is ever so slightly better!

**Comment by scott-griffiths** [comment]
Reopening just to make the issue more visible, as this seems to be tripping up a few people. If you really need 3.1.3 then you can get it via the git repository, otherwise you should be using 3.1.4.

**Comment by boegel** [comment]
@scott-griffiths getting 3.1.3 back up on PyPI would be much appreciated...

Have you tried via this link (once logged in to PyPI)?

https://pypi.python.org/pypi?:action=files&name=bitstring&version=3.1.3

**Comment by scott-griffiths** [comment]
Yes, I've tried that - you can't upload a file with the same name as a previous file. So I can't call it 3.1.3. And calling it anything else wouldn't work. 

The fix is to use 3.1.4 instead - is there any reason this doesn't work or is difficult for you?

**Comment by boegel** [comment]
Our recipes for Python 2.7.11 include bitstring 3.1.3, and we prefer sticking to that (we don't bump versions in existing recipes), cfr .https://github.com/hpcugent/easybuild-easyconfigs/issues/2819

Of course, we can download the source tarball from this GitHub repo though.

But still, I'm hoping for a way to actually fix this on PyPI. It's very hard to grasp the fallout that this may have...

See for example http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/ (not Python, but it gives a good idea of what *can* happen when stuff disappears 'upstream').

**Comment by scott-griffiths** [comment]
I'll get in touch with PyPI when I can and see what they suggest. Cheers.

**Comment by boegel** [comment]
@scott-griffiths ping on this?

**Comment by scott-griffiths** [comment]
I don't think this is going to happen any time soon. PyPI don't seem to be able to get download counts or even pointing to the latest version of a module right, so this problem seems a low priority.

Just released 3.1.5. I'll try not to accidentally delete any old versions again, but I think that's the best I can do.
