### ISSUE TITLE
Initialising hex and oct from long integers not straightforward

### ISSUE THREAD

**Issue by scott-griffiths** [scott-griffiths/bitstring#163]
Presumably only a Python 2 problem:

a = BitArray()
a.hex = hex(9999999999999999999999999)

causes CreationError because the hex value returned ends in 'L'.

We get the same problem with
a.oct = oct(999999999999999999999999999)

Strangely 'bin' works fine!

**Comment by AnyMaster** [comment]
probably, as far as you have tidy_input_string(),  instead of **some_var= some_var.replace('0x', '')** it will be better to use lstrip() and rstrip() like:

**"qsszl".lstrip("q").rstrip("l")
 'ssz'**

**Comment by scott-griffiths** [comment]
I'm calling this a Python 2.7 issue and not a bitstring issue. Basically if you give an input with an 'L' in it then it won't be able to convert it to hex or oct. Solution is to not give it input with an 'L' in it! It's true that the 'L' is implicit, but it's still there and can be dealt with by the user quite easily.
