### ISSUE TITLE
Missing char and char[] conversions

### ISSUE THREAD

**Issue by urosjarc** [scott-griffiths/bitstring#167]
This lib is missing very important conversions (char and char[ ] ).
I would really like this to be implemented in the bitstring so that I can finaly dump [struct lib](https://docs.python.org/2/library/struct.html) once and for all.

**Comment by scott-griffiths** [comment]
I'm not sure what you mean - char and char[] aren't part of the Python language.

Can you give more detail - maybe example code of what you'd like to be able to do?

**Comment by urosjarc** [comment]
For example you have word packed into binary package and you want to get ascii representation of this word in `utf-8` codings. [Here in docs](https://pythonhosted.org/bitstring/packing.html) I could not see how to achive this thing.

Curently I'm doing this to get ascii word out of binary string...
```
ascii = struct.unpack('{}p'.format(len(bin)),bin)
```
