### ISSUE TITLE
Interpret file contents as hexadecimal string

### ISSUE THREAD

**Issue by HagaiHargil** [scott-griffiths/bitstring#169]
I have a file with strings that represent hexadecimal digits. Since they don't have any "0x" prefix, both Python (3.x) and your module reads them as bytearrays, turning every character into a full-blown byte, instead of a hexadecimal string. 

For example, in the file a data line might look like `0100000060d9`, which should be interpreted as a 48-bit long word (12 characters, 4 bits per char) but is instead interpreted as a 96-bit long word.

Currently, using either `numpy` or the `array` module I'm able to read the file in binary mode to an array, decode it to a string, add a `0x` prefix and then continue to process this data list using this great package. Unfortunately, since I have quite large datasets, all of this pre-processing is expensive, and I'd be very happy to avoid it. 

Is there a way to interpret every byte as a hexadecimal digit directly?

**Comment by scott-griffiths** [comment]
If you want it to interpret as hex then you need to tell the constructor. Something along the lines of

s = Bits(hex='01000000060d9')

should work as you want. Take a look at the manual for more ways to construct bitstrings. To interpret the bitstring you can then use

s.hex

or 

s.bytes

which should do what you expect.

**Comment by HagaiHargil** [comment]
Hi @scott-griffiths, thanks for the prompt reply! You can be certain that I read through the manual a couple of times before coming here :)

Let me try to rephrase my question, I guess I wasn't clear enough: I have a data file consisting of lines in this format:
```
0100000060d9\r\n
010000008289\r\n
...
```
These are hexadecimal strings, and not bytes. Unfortunately, when I open the file using `data = ConstBitStream(filename=filename)` Python and `bitstring` will treat each line as a bytearray:
```
b'0100000060d9\r\n'
b'010000008289\r\n'
...
```
turning each hexadecimal digit to a byte.

Thus, calculating the `.hex` property of them isn't useful to me - they should already by considered hex. I also can't use the constructor on bytestrings to "force" them into being hexadecimal digits, due to a `TypeError - expected str instance, bytes found`.

The solution I'm looking for might be to make `bitstring` treat these bytestrings, straight out of my file, as hexadecimal digits, and not bytes.

I hope it makes things more clear.

**Comment by scott-griffiths** [comment]
OK, well as it's Python 3 it treats a bytes object as just bytes, so if you want it to behave like a string you need to explicitly convert it to one. One way of doing this is

str_object = byte_object.decode('utf-8')

Now that's a bit awkward to do, but I think is the proper way. The problems is that you need to tell it that the bytes are really just a string which have only hex characters - there's no way that bitstring can infer it

In Python 2 there isn't really a distinction between str and bytes so this would work differently - you'd have to explicitly use the bytes= initialiser to make it treat it as bytes rather than a str.

**Comment by HagaiHargil** [comment]
I see.

My current solution, which seems the fastest ATM, is to read the file to an `array.array`, decode it and finally set it as a ConstBitStream:

```
with open(filename, 'rb') as f:
  f.seek(start_of_data)
  arr = array.array('B')
  try:
    arr.fromfile(f, file_size)
  except EOFError:
    arr_str = '0x' + arr.tobytes().decode('utf-8')
    bitstream = ConstBitStream(arr_str)
```
Thanks a lot for your help.
