### ISSUE TITLE
32 tests failing??

### ISSUE THREAD

**Issue by npandita19** [scott-griffiths/bitstring#171]
@scott-griffiths 
I tried running the tests provided, and 32 of them failed. All because of missing files: test.m1v
and smalltestfile. I can see them under test folder. Am I supposed to make some PATH changes?
Below is the stacktrace of 2 such failures:-
======================================================================
ERROR: testFileBasedCopy (test_bitstream.Split)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "MY_PATH\bitstring-master\test\test_bitstream.py", line 2352, in testFileBasedCopy
    with open('smalltestfile', 'rb') as f:
IOError: [Errno 2] No such file or directory: 'smalltestfile'

======================================================================
ERROR: testPrint (test_bitstream.Split)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "MY_PATH\bitstring-master\test\test_bitstream.py", line 1916, in testPrint
    s = BitStream(filename='test.m1v')
  File "MY_PATH\bitstring-master\bitstring.py", line 4133, in __new__
    x._initialise(auto, length, offset, **kwargs)
  File "MY_PATH\bitstring-master\bitstring.py", line 829, in _initialise
    init_with_length_and_offset[k](self, v, length, offset)
  File "MY_PATH\bitstring-master\bitstring.py", line 1301, in _setfile
    source = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: 'test.m1v'

**Comment by scott-griffiths** [comment]
Thanks for letting me know. It works for me, so I've probably got some old environment variables set up. Copying the two test files to the test directories should be a quick hack to fix it, but once I get around to confirming on a clean machine I'll fix the root problem.

**Comment by scott-griffiths** [comment]
Fixed on 3.1-update branch.
