### ISSUE TITLE
Problem with bitstring

### ISSUE THREAD

**Issue by AliVideo** [scott-griffiths/bitstring#179]
It seems there is an error with this syntax: bitstring.pack...
I have got error while typing this command (this is in documentation): 
```
w, h = 352, 288
s = bitstring.pack('0x000001b3, 2*uint:12', w, h)
```

and the error is: 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'bitstring' is not defined

**Comment by scott-griffiths** [comment]
Looks like bitstring is not defined so presumably nothing will work?

The only prerequisite for that line to work is that you've installed the module and imported it.
