### ISSUE TITLE
__contains__ traceback in python 2.7

### ISSUE THREAD

**Issue by soggysec** [scott-griffiths/bitstring#180]
__contains__ is failing when checking if one bit object exists within another

`Bits(hex="deadbeef")` in Bits(hex="deadbeef")`

/usr/local/lib/python2.7/dist-packages/bitstring.pyc in __contains__(self, bs)
   1157         found = Bits.find(self, bs, bytealigned=False)
   1158         try:
-> 1159             self._pos = pos
   1160         except AttributeError:
   1161             pass

UnboundLocalError: local variable 'pos' referenced before assignment

**Comment by scott-griffiths** [comment]
Thanks. Very strange - even the documented examples don't work so something went badly wrong somewhere. Very surprised the unit tests didn't pick it up too...

**Comment by soggysec** [comment]
Sure thing! Any idea when it’ll get merged with master? It’s a kind of big issue for one of my workflows at the moment.

Thanks

**Comment by scott-griffiths** [comment]
Not sure when it will get fixed/released. I have enough to justify a 3.1.6 so I really should try to get round to it soon. A simple workaround if you don't want to use 'unofficial' code is to recode with a find() instead.

**Comment by soggysec** [comment]
I actually provided a pull request that fixed it. It should be referenced in this thread

Sent from iPhone
________________________________

**Comment by scott-griffiths** [comment]
Fixed on 3.1-update branch (will get merged to master once 3.1.6 is released).
