### ISSUE TITLE
__getitem__ reduces the length of the bit word.

### ISSUE THREAD

**Issue by oversun1** [scott-griffiths/bitstring#185]
>>> print(bitstring.__version__)
3.1.5
>>> s = bitstring.Bits('0b111')
>>> s
Bits('0b111')
>>> s[0:2]
Bits('0b11')
>>> s[1:3]
Bits('0b11')
>>> s[0:3]
Bits('0b111')
>>>

**Comment by scott-griffiths** [comment]
Hi. Not sure what you expect to get here. The behaviour matches what you'd get with an ordinary list `s = [1, 1, 1]`

What did you expect to get?

**Comment by oversun1** [comment]
I am newbie. I an wrong.

**Comment by scott-griffiths** [comment]
No problem!
