### ISSUE TITLE
Can't initialize bitstring correctly from  BytesIO file object

### ISSUE THREAD

**Issue by kaganAl** [scott-griffiths/bitstring#189]
Known bug in my place of work.
Initialization doesn't throw any exception.
get value and read methods return incorrect result. We assume that it happens because _setauto method tries to access the file in the filesystem and to retrieve the length parameter from it while there is no such a file in fs when BytesIO object is used.

**Comment by scott-griffiths** [comment]
Thanks for the report. I'll try to add support soon.

**Comment by scott-griffiths** [comment]
Fixed in 3.1.7
