### ISSUE TITLE
Please add support for Python3_{7,8}

### ISSUE THREAD

**Issue by onkelbeh** [scott-griffiths/bitstring#193]
Hi Scott,

first thanks for your work. Could you please add support for Python3_{7,8}?
I am using some integrations for Home Assistant which depend on your library.
Home Assistant drops 3.6 support in mid of december.

I can confirm it runs without problems on 3.7, inho it's just missing in some of the frameworks textfiles. I now use an [extended gentoo ebuild](https://github.com/onkelbeh/HomeAssistantRepository/commit/f2d15a9c91c29f38bfa28a76981084d62d8a7ad0) for it in my [Gentoo Overlay for Home Assitant.](https://github.com/onkelbeh/HomeAssistantRepository)

Did not test it with 3.8 yet, but migration is starting soon.

Thanks a lot.
 \B.

**Comment by scott-griffiths** [comment]
Hi. It should be totally straightforward so I'll try and get it done with a couple of other minor things. Can't promise any timeframe but hopefully I'll get the chance quite soon.

**Comment by scott-griffiths** [comment]
Fixed in 3.1.7 (not quite as soon as I'd hoped).
