### ISSUE TITLE
Stop supporting Python 2.7?

### ISSUE THREAD

**Issue by scott-griffiths** [scott-griffiths/bitstring#195]
As Python 2.7 development is now frozen it might make sense to do the same for this module. Removing the need to support 2.7 would allow some ugly code to be removed, plus some newer methods could be used, especially if early 3.x releases also become unsupported.

For example the int.to_bytes() and int.from_bytes() methods were added in Python 3.2. Around 80% of Python 3 downloads are Python 3.6 or greater, so that seems a reasonable version to target (and it means I can use 'f' format strings!)

Most downloads are still Python 2.7, so I don't intend to abandon it, it's just that the Python 3.6 version may end up faster and with exclusive new features in the longer term.

So perhaps bitstring 3.2.x becomes the final Python 2.7 supporting minor version, and bitstring 3.3 onwards is Python 3.6+ only.

**Comment by florisla** [comment]
Some users will remain on Python 2.7 (RedHat RHEL has very long support cycles for example)  but they can continue to use existing releases of bitstring, so that's fine.

Python.org drops Python 3.5 support in September: https://devguide.python.org/#status-of-python-branches

**Comment by Theelgirl** [comment]
I would like to say that, to the extent of my knowledge, according to [Semver 2.0](https://semver.org/#spec-item-8), if Python 2.7 support is dropped then that breaks backwards compatibility, and therefore requires a major version bump, so this should be implemented in bitstring 4.0.

I do fully support bitstring dropping Python 2.7 support though.

**Comment by scott-griffiths** [comment]
Interesting point, but I'd argue that there is no backward compatibility lost. If you're using a supported version of Python then bitstring 3.2 will be backwards compatible. If you're not using a supported version of Python then bitstring 3.2 won't be available!

I'd have to test it but I don't think anyone running Python 2.7 will be able to update to bitstring 3.2 via the standard installation tools if the setup.py says it isn't supported.

**Comment by scott-griffiths** [comment]
Changing milestone to 4.0 as I agree it will be easier to communicate the change that way.

**Comment by felixdivo** [comment]
> Around 80% of Python 3 downloads are Python 3.6 or greater, so that seems a reasonable version to target (and it means I can use 'f' format strings!)

It would also allow for using [type hints](https://docs.python.org/3/library/typing.html) (introduced in Python 3.5), if one wanted to use it. Might be helpful for communicating what the interfaces accept and output.

**Comment by scott-griffiths** [comment]
Done on the 4.0-update branch. Minimum changed to Python 3.7. Will become a release hopefully fairly soon.
