### ISSUE TITLE
Importing ABC directly from collections module was removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [scott-griffiths/bitstring#196]
https://bugzilla.redhat.com/show_bug.cgi?id=1792933

https://github.com/scott-griffiths/bitstring/blob/e886c888c22dbfa702da6b0e27804e98e916b16c/bitstring.py#L1314

https://github.com/scott-griffiths/bitstring/blob/e886c888c22dbfa702da6b0e27804e98e916b16c/test/test_bitstream.py#L3460

Thanks for the library!

**Comment by scott-griffiths** [comment]
Thanks for letting me know. I should be able to add a fix in the next point release.

**Comment by tirkarthi** [comment]
You're welcome. If you haven't started work on this, I can raise a PR for this.

**Comment by scott-griffiths** [comment]
Fixed in 3.1.7
