### ISSUE TITLE
Issue importing module

### ISSUE THREAD

**Issue by adriangabura** [scott-griffiths/bitstring#198]
Hey!
So I have an issue importing the module in scripts. When I write import bitstring in the interpreter it works. When I try in scripts it doesn't. I tried on a couple of systems. And results are weird to say the least. On a win 2019 server with python 3.8 it loads fine. On a fedora 30 with python 3.7 works fine. On another fedora it doesn't. And on two windows 10 it doesn't work except in the interpreter. So.... what could be the issue? Something is definitely wrong but I can't pin it. I tried 3.6.8 on the problematic systems and it doesn't help.

**Comment by scott-griffiths** [comment]
Well you don't give any details about how it doesn't work, but I'm pretty sure it's not the module at fault. Best guess is either there are multiple Pythons installed and it's not installed on them all or it's picking up bitstring.py from a local file rather than from site-packages.

**Comment by adriangabura** [comment]
Sorry about lack of details... The issue that I get is an circular import error when I'm trying to execute the script. I'm not doing anything fancy, I'm just trying to check the module and see if it will fit my program paradigm. Thanks!

**Comment by adriangabura** [comment]
Ok I figured it out. I am very very sorry for bothering you. I created a bitstring.py script and imported bitstring in it. I'll remember this for the future.

**Comment by scott-griffiths** [comment]
No problem.
