### ISSUE TITLE
pack not defined error

### ISSUE THREAD

**Issue by TracyWel** [scott-griffiths/bitstring#199]
I'm a noob to Python, so I fear this is going to be a stupid question. But I have scoured the bitstring documentation and tested all I can think of.

I've got the following import statement early in the script:
from bitstring import Bits, BitArray, BitStream, ConstBitStream

I've copied in this from the documentation: 
s = pack('uint:10, hex, int:13, 0b11', 130, '3d', -23)

But at exectution it throws this error: 
NameError: name 'pack' is not defined.

**Comment by scott-griffiths** [comment]
Hi, the problem is that pack is a module level function, so you either need to import it specifically ('from bitstring import pack') or just 'import bitstring' and use it as 'bitstring.pack'.

**Comment by TracyWel** [comment]
Excellent! Thanks. I’m finding these tools to be very powerful.

**Comment by TracyWel** [comment]
Thanks! it works.
