### ISSUE TITLE
Can't open official website?

### ISSUE THREAD

**Issue by jekoie** [scott-griffiths/bitstring#208]
I can't open https://pythonhosted.org/bitstring/ ?, it's website is ok?

**Comment by scott-griffiths** [comment]
The pythonhosted documentation site stopped accepting new or updated docs quite some time ago. The new docs are at https://bitstring.readthedocs.io/ 

I recently deleted the pythonhosted docs as they were getting out of date and I couldn't change them. The old docs are still pointed to by some searches, but shouldn't be anywhere 'official'. If there's a link to the old docs that I need to change then please let me know.

Thanks.

**Comment by jekoie** [comment]
ok , i will.
