### ISSUE TITLE
Read file bits in chunks

### ISSUE THREAD

**Issue by marvic2409** [scott-griffiths/bitstring#209]
I know the BitArray class exists and I was wondering if it was possible to create a bit array for chunks of a file and then merge them (When trying to read the bits of a massive file, it freezes up as it loads it all to ram)

**Comment by scott-griffiths** [comment]
Take a look at the ConstBitArray class. This won't load files into memory except for the chunks you reference directly. The non-const classes need to load files into memory as they are mutable types.
