### ISSUE TITLE
Endianness support for non byte-aligned values

### ISSUE THREAD

**Issue by jcbooth2** [scott-griffiths/bitstring#210]
For example if I wanted to create a little-endian unsigned integer of only length 12, the interface could be the same as what already exists:

bits = Bits(uintle=value, length=12)

**Comment by scott-griffiths** [comment]
Hi. Sorry for the delay. I'm not sure you've got the terminology correct in your question. The endian representations deal in which order the whole bytes that make up the number are used to construct the integer - this doesn't make sense if the integer isn't a whole number of bytes long.

What you might be asking about is the ability to read the whole integer 'backwards' bit by bit. This is covered in the on-going request #156.

If that's not what you're asking about could you provide a concrete example of what you expect to happen with the code snipped you gave. Thanks.
