### ISSUE TITLE
QUESTION: What is the fastest way of iterating through the bits in a ConstBitStream?

### ISSUE THREAD

**Issue by obvionaoe** [scott-griffiths/bitstring#213]
Hi, I was wondering if there is any way to iterate through a ConstBitStream faster than:

```
while 1:
    stream.read(1)
```

Thank you

**Comment by scott-griffiths** [comment]
Hi. It depends on what you want to do with the bits. It's unusual to want to read single bits in sequence like that, but for example if you want to count how many 1s are present then you can use the `count` method on the stream. If you're looking for the first `1` in the stream then use `find` and so on. Difficult to give a general answer without knowing the problem a bit better.

**Comment by obvionaoe** [comment]
I'm writing a compression algorithm(I know python is not the best for such task but my teacher asked for it xD), so I really have to read 1 bit at a time :smile: 

I would like to know though, if I had this code:
```
t = ConstBitStream(bin='01001')
t.read(1)
```

How can I tell that I still have 4 bits to read? I've tried checking the length of `t` but it is constant(as it should because it is not consuming anything)

Is there an easy way to do this?

**Comment by scott-griffiths** [comment]
Sorry, this is a very late response, but for the record I think you were looking for the `pos` attribute.
