### ISSUE TITLE
improper results when using readlist('intle:16, 16, 16')

### ISSUE THREAD

**Issue by mmadela** [scott-griffiths/bitstring#215]
output from 
`readlist('intle:16, 16, 16')`
differs from the one produced by 
`readlist('intle:16, intle:16, intle:16')`

according documentation the shorter form is legal

**Comment by scott-griffiths** [comment]
I'm not sure what part of the documentation you're referring to, but those two reads are different - there's no state saved from one element to the next so they aren't going to be `intle`.

You can instead use `'3*intle:16'` in this case though.
