### ISSUE TITLE
distribute wheels

### ISSUE THREAD

**Issue by sander76** [scott-griffiths/bitstring#216]
I am trying to use bitstring in combination with pynsist to build a build a windows installer:

https://pynsist.readthedocs.io/en/latest/index.html

However, pynsist only consumes `wheel` files as packages (which I see as a fair limitation as wheels are nowadays the default distribution format). Is it possible to include these in upcoming releases ?

Thanks !

**Comment by sander76** [comment]
Some suggested changes: https://github.com/scott-griffiths/bitstring/pull/217

**Comment by scott-griffiths** [comment]
This should now work for the 3.1.8 release.
