### ISSUE TITLE
Switching bit order?

### ISSUE THREAD

**Issue by IamMusavaRibica** [scott-griffiths/bitstring#218]
Say we have this bit stream: `00000111 00000101 10010000 00011001` (spaces for easier reading)
Is it possible to change the bit order / endianness of each byte in it? So for example, first one becomes `11100000`, second `10100000` etc.
I need the least significant bit read first 
I know its possible for **bytes**, but what about **bits**?
Thanks in advance

**Comment by scott-griffiths** [comment]
The easiest way to do this is to reverse all the bits, then reverse the bytes:

```
    s = bitstring.BitArray('0b00000111 00000101 10010000 00011001')
    s.reverse()
    s.byteswap()

>>> s.bin
'11100000101000000000100110011000'

```
For large amounts of data this won't be very efficient though.

**Comment by IamMusavaRibica** [comment]
Thank you! I won't handle large amounts of data though, maximum of 16 bytes
at once so this will be much useful!

pon, 3. svi 2021. u 13:44 Scott Griffiths ***@***.***>
napisao je:
