### ISSUE TITLE
"Minified" version/s

### ISSUE THREAD

**Issue by ChanceNCounter** [scott-griffiths/bitstring#219]
I'm probably weeks out, but it's my present intention to see if I can split the classes and reduce imports to the bare minimum, thereby creating an even smaller version of `bitstring`.

This is not due to any particular gripe; on the contrary, I use `bitstring` on a regular basis and I absolutely love it. Rather, I'm embarking on a perhaps futile quest to see how small I can make a wss stack and a particular binary protocol, so I mean to cut every last byte my deps can spare.

I'm bringing this up in case you'd prefer to own that repo and package that fork. For my purposes, it would just be a difficult-to-sync downstream for a particular project, and I'm not looking to take on any new repos, so I probably wouldn't publish or package it. However, others might find it useful.

**Comment by scott-griffiths** [comment]
Hi, glad you're finding bitstring useful. I suspect you could cut a great deal quite easily for any particular use case - probably fairly straightforward. I'm far too occupied to take on any new repos right now, but best of luck! Hopefully it won't be difficult to sync as even now you only need to distribute a single source file.

**Comment by ChanceNCounter** [comment]
Fair enough, and thanks again for a great module!
