### ISSUE TITLE
distutils is deprecated in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [scott-griffiths/bitstring#224]
https://www.python.org/dev/peps/pep-0632/#migration-advice . Since setuptools is available using setup from setuptools will fix this.

https://github.com/scott-griffiths/bitstring/blob/c84ad7f02818caf7102d556c6dcbdef153b0cf11/setup.py#L4

**Comment by scott-griffiths** [comment]
Moved over to just using pyproject.toml in version 4, so setup.py removed completely!
