### ISSUE TITLE
Bits.findall does not support LSB0 numbering

### ISSUE THREAD

**Issue by andreas-0815-qwertz** [scott-griffiths/bitstring#236]
I am a happy user of the experimental LSB0 support.  `Bits.findall` still returns indices in MSB0.

Currently, I am using the following workaround for the results of `Bits.findall` (with `bs` being an instance of `Bits`):

`list(reversed( [len(bs) + (-i - 1) for i in bs.findall([1])]`

I am using bitring version 3.1.9.

**Comment by scott-griffiths** [comment]
Hi. Yes you're right that `findall` isn't working with lsb0 yet. I'm trying to fix the remaining issues with the LSB0 to finally release it as a proper feature in version 4, but there are still quite a few edge cases to test and fix.

There's better support for LSB0 on the main branch (and the 4.0-update branch), but not yet for findall.

Thanks.

**Comment by scott-griffiths** [comment]
There are still a few known issues with streaming methods, but the basic functionality should all be there in version 4.0 (including findall).
