### ISSUE TITLE
Interested in a PR for a GitHub Actions CI setup?

### ISSUE THREAD

**Issue by altendky** [scott-griffiths/bitstring#242]
Would you be interested in a PR adding a GitHub Actions CI setup for bitstring?  Shouldn't take too long to get the basic platform (Intel anyways, not-ARM)  and supported Python version checks going.

**Comment by scott-griffiths** [comment]
Yes, that would be helpful. I used to have Travis CI set up, but that setup died and I didn't like their new terms and conditions.
