### ISSUE TITLE
Please remove 4.0.0b1 release from pypi

### ISSUE THREAD

**Issue by selimt** [scott-griffiths/bitstring#259]
In a Python 2.7 environment, pip tries to install the `4.0.0b1` release of bitstring which is not compatible with 2.7:

```
> pip install --use-deprecated=legacy-resolver bitstring== --index-url https://pypi.python.org/simple/
Looking in indexes: https://pypi.python.org/simple/
ERROR: Could not find a version that satisfies the requirement bitstring== (from versions: 0.3.2, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.5.2, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0, 1.3.0, 2.0.0b1, 2.0.1b2, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.1.1, 3.1.2, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 4.0.0b1)
ERROR: No matching distribution found for bitstring==
```

Thanks.
-Selim

**Comment by scott-griffiths** [comment]
Hmmm. Not sure why it turns up in that list, but it shouldn't be a problem unless you actually ask for that beta specifically (and betas don't have any guarantees that they will work!)

The Pypi page for that release doesn't suggest it supports 2.7, but possibly it was misconfigured. So I don't think it should be causing any problems, but equally it's not needed any more and it only takes one more click to remove it so I'll do so.

Version yanked. It shouldn't show up any more.
