### ISSUE TITLE
Stray, invalid `bitstring/plugin_test.py` in the sdist for 4.1.2

### ISSUE THREAD

**Issue by mgorny** [scott-griffiths/bitstring#293]
The sdist contains a `bitstring/plugin_test.py` file that doesn't seem to be present in the git repository here, and that has invalid syntax:

```pytb
  File "/tmp/portage/dev-python/bitstring-4.1.2/work/bitstring-4.1.2/bitstring/plugin_test.py", line 8
    reverse_int = Dtype(name='uintr', getter=getuintr, setter=setuintr)
    ^
IndentationError: expected an indented block after function definition on line 6
```

**Comment by scott-griffiths** [comment]
Good catch - thanks for letting me know. 

Also there's a similarly stray `hints.py`, both of which got dragged into the PyPI sdist upload (but not the GitHub sdist). Neither file is terribly interesting, and I don't think they'll cause problems, but clearly my release procedure needs some work. 😞 

I'll fix in another update shortly. Again, thanks for the heads up as that could have been worse.

**Comment by scott-griffiths** [comment]
Sorted in 4.1.3 release.

**Comment by mgorny** [comment]
Thanks!
